spring:
  application:
    name: posth
  datasource:
    url: "jdbc:mysql://193.122.123.213:3306/posth"
    username: "posth"
    password: "posth"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "QmTz2nhwYgOQ4iKspZrCdAbG+Uw7EMrHtwl0VhA1bS0="
